### ISSUE TITLE
[BUG] Die Fortschritte der Erfolge setzen sich zurück

### ISSUE THREAD

**Issue by L4mpo** [raidcraft/rcachievements#74]
Hey, bei mir und weiteren Spielern (bspw. Xedeone) ist der Bug aufgetreten, dass die Fortschritte der Erfolge immer wenn man sich ausloggt sich zurücksetzen. Bereits erhaltene Erfolge behält man aber man ist halt immer auf 0/xyz.
Den Bug kann man Reproduzieren, indem man z.B. 5 Diamanten aubbaut und sich dann ausloggt, danach ist man wieder auf 0. Gleiches Problem übrigens auch bei den Erfolgen die zum Weltenbummler gehören.
Screenshots sind glaube nicht von nöten aber ich habe mal meine Diamanten Erfolge angehangen.
Der Bug löst sich im Mining aus und ist (meines wissens nach) gestern aufgetreten. 
Was man noch wissen sollte, ist dass das nicht bei allen Erfolgen auftritt, bei Sand und Erde bleibt es z.B. gespeichert.
Wenn noch fragen ist, ich behalten den Report in Augen und beantworte dann :p
![2021-03-06_11 29 32](https://user-images.githubusercontent.com/69364013/110203597-5c4dbc00-7e6f-11eb-9426-5b612ec49435.png)

**Comment by Silthus** [comment]
Kannst du bitte mal folgendes testen:

1. Ein Mineral abbauen bei dem nachweislich der Bug auftritt
2. Auf dem **Mining** Server ausloggen
3. Prüfen ob der Bug aufgetreten ist

1. Ein Mineral abbauen bei dem nachweislich der Bug auftritt (nicht das gleiche wie im ersten Test)
2. Auf dem **Main** Server ausloggen
3. Prüfen ob der Bug aufgetreten ist

- Werden beim Weltenbummler alle Fortscrhitte bei jedem Logout auf 0 gesetzt oder nur bei manchen Erfolgen?
- Weißt du zufällig bei welchem Block Abbau Erfolgen der Bug **nicht** auftritt?
- Betrifft der Bug bei dir und jemand anderem die gleichen Erfolge?

**Comment by L4mpo** [comment]
> Kannst du bitte mal folgendes testen:
> 
> 1. Ein Mineral abbauen bei dem nachweislich der Bug auftritt
> 2. Auf dem **Mining** Server ausloggen
> 3. Prüfen ob der Bug aufgetreten ist
> 
> Und dann bitte das hier noch:
> 
> 1. Ein Mineral abbauen bei dem nachweislich der Bug auftritt (nicht das gleiche wie im ersten Test)
> 2. Auf dem **Main** Server ausloggen
> 3. Prüfen ob der Bug aufgetreten ist
> 
> * Werden beim Weltenbummler alle Fortscrhitte bei jedem Logout auf 0 gesetzt oder nur bei manchen Erfolgen?
> * Weißt du zufällig bei welchem Block Abbau Erfolgen der Bug **nicht** auftritt?
> * Betrifft der Bug bei dir und jemand anderem die gleichen Erfolge?

Der Bug ist nun seltsamer weiße weg also es wird derzeit nichts zurückgesetzt (egal wo man sich ausloggt), ich beantworte trotzdem mal deine Fragen. Alle neueren Erfolge, wie Sand, Erde und Redstone blieben erhalten. Alle äteren wie Eisen, Diamanten und der Weltenbummler kram wurde zurückgesetzt. Es trat auch nicht nur bei mir auf sondern auch bei xedeone und Dunkel (evtl auch mehr aber bei den weiß ich es). Und es betrifft soweit ich weiß bei jedem die gleichen Erfolge, also es wurde bei uns allen der Weltenbummler kram zurückgesetzt, 
MfG
